import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";
import { House, Search, SquarePlay, SquarePlus, CircleUserRound } from 'lucide-react';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Baat Cheet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative pb-10`} >
        <Header />
        {children}
        <div className="md:hidden fixed bottom-0 flex justify-around items-center border-t w-full p-3 bg-white">
          <House className=" h-7 w-7" />
          <Search className=" h-7 w-7" />
          <SquarePlus className=" h-7 w-7" />
          <SquarePlay className=" h-7 w-7" />
          <CircleUserRound className=" h-7 w-7" />
        </div>
      </body>
    </html>
  );
}
